title: "Cybersecurity Blog"
description: "Documenting my cybersecurity learning journey & homelab projects"
baseurl: "/cybersecurityblog"
url: "https://bytepo1arbear.github.io"
permalink: /:year/:month/:day/:title/

collections:
  projects:
    output: true
  writeups:
    output: true
  resources:
    output: true

theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
