title: "BytePolarBear's Cybersecurity Blog"
author: "Jack"
description: "A blog documenting my cybersecurity journey, ethical hacking projects, and technical writeups."
layout: default
baseurl: ""
collections:
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
    layout: post
